# Translation of Odoo Server.
# This file contains the translation of the following modules:
# 	* base_rest_demo
#
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 16.0\n"
"Report-Msgid-Bugs-To: \n"
"PO-Revision-Date: 2024-01-15 11:35+0000\n"
"Last-Translator: mymage <stefano.consolaro@mymage.it>\n"
"Language-Team: none\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Generator: Weblate 4.17\n"

#. module: base_rest_demo
#. odoo-python
#: code:addons/base_rest_demo/services/exception_services.py:0
#, python-format
msgid "Access error message"
msgstr "Messaggio errore accesso"

#. module: base_rest_demo
#. odoo-python
#: code:addons/base_rest_demo/services/exception_services.py:0
#, python-format
msgid "Missing message"
msgstr "Messaggio perdita"

#. module: base_rest_demo
#. odoo-python
#: code:addons/base_rest_demo/services/partner_image_services.py:0
#, python-format
msgid "No image found for partner %s"
msgstr "Nessuna immagine per il partner %s"

#. module: base_rest_demo
#. odoo-python
#: code:addons/base_rest_demo/services/exception_services.py:0
#, python-format
msgid "UserError message"
msgstr "Messaggio errore utente"

#. module: base_rest_demo
#. odoo-python
#: code:addons/base_rest_demo/services/exception_services.py:0
#, python-format
msgid "ValidationError message"
msgstr "Messaggio errore validazione"
